import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    const { data: session } = useSession();

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}></main>
            {session ? (
                <div>
                    {" "}
                    Signed in as
                    {session.user?.email}
                    <button onClick={() => signOut()}> Sign out</button>
                </div>
            ) : (
                <div>
                    Not signed in
                    <button
                        className="px-5 py-2 border-2 bg-gray-500 text-white"
                        onClick={() => signIn()}
                    >
                        Signin
                    </button>
                </div>
            )}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Designed by 🐈
                </a>
            </footer>
        </div>
    );
};

export default Home;
